### ISSUE TITLE
jspm beta support

### ISSUE THREAD

**Issue by guybedford** [aurelia/bootstrapper#10]
When doing the System.import for a package, the new defaultJSExtensions will provide a `.js` extension at the end of the package name causing Aurelia not to work in jspm beta.

To make this easier I've added the ability to run `System.normalize('package/name/')` where the trailing `/` then does not automatically add the js extension. This can be tested by running jspm beta with `jspm dl-loader --edge`. Then the dynamic imports can be updated to do the above normalization style where necessary.

I'm hoping to make the beta the primary release soon, but will wait until this is fixed. If there's any other issues I can help with just let me know.

**Comment by EisenbergEffect** [comment]
Where exactly is this breaking things? Is it breaking our view loading?

**Comment by MicahZoltu** [comment]
It breaks half way through the bootstrapping process.  This `index.html` file alone will cause the bug to reproduce:

``` html
<!doctype html>
<html>
<body aurelia-app>
    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
        System.import('aurelia-bootstrapper');
    </script>
</body>
</html>
```

It never gets to the point where it tries to load `app.js` or `app.html`.

**Comment by guybedford** [comment]
Here's the debug log - 

```
NFO [aurelia] Aurelia Starting
jspm_packages/github/aurelia/logging-console@0.5.0/index.js:41 DEBUG [aurelia] Loading plugin file:///Users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-binding@0.12.0.js.
jspm_packages/github/aurelia/logging-console@0.5.0/index.js:41 DEBUG [aurelia] Configured plugin file:///Users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-binding@0.12.0.js.
jspm_packages/github/aurelia/logging-console@0.5.0/index.js:41 DEBUG [aurelia] Loading plugin file:///Users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-resources@0.12.1.js.
jspm_packages/github/aurelia/logging-console@0.5.0/index.js:41 DEBUG [aurelia] Configured plugin file:///Users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-resources@0.12.1.js.
jspm_packages/github/aurelia/logging-console@0.5.0/index.js:41 DEBUG [aurelia] Loading plugin file:///Users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/history-browser@0.5.0.js.
jspm_packages/github/aurelia/logging-console@0.5.0/index.js:41 DEBUG [aurelia] Configured plugin file:///Users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/history-browser@0.5.0.js.
jspm_packages/github/aurelia/logging-console@0.5.0/index.js:41 DEBUG [aurelia] Loading plugin file:///Users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-router@0.13.0.js.
jspm_packages/github/aurelia/logging-console@0.5.0/index.js:41 DEBUG [aurelia] Configured plugin file:///Users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-router@0.13.0.js.
jspm_packages/github/aurelia/logging-console@0.5.0/index.js:41 DEBUG [aurelia] Loading plugin file:///Users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/event-aggregator@0.5.0.js.
jspm_packages/github/aurelia/logging-console@0.5.0/index.js:41 DEBUG [aurelia] Configured plugin file:///Users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/event-aggregator@0.5.0.js.
system.js:1020 XMLHttpRequest cannot load file://users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-resources@0.12.1.js/compose.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ system.js:1020
system.js:1020 XMLHttpRequest cannot load file://users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-resources@0.12.1.js/if.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ system.js:1020
system.js:1020 XMLHttpRequest cannot load file://users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-resources@0.12.1.js/with.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ system.js:1020
system.js:1020 XMLHttpRequest cannot load file://users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-resources@0.12.1.js/repeat.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ system.js:1020
system.js:1020 XMLHttpRequest cannot load file://users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-resources@0.12.1.js/show.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ system.js:1020
system.js:1020 XMLHttpRequest cannot load file://users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-resources@0.12.1.js/replaceable.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ system.js:1020
system.js:1020 XMLHttpRequest cannot load file://users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-resources@0.12.1.js/global-behavior.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ system.js:1020
system.js:1020 XMLHttpRequest cannot load file://users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-resources@0.12.1.js/sanitize-html.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ system.js:1020
system.js:1020 XMLHttpRequest cannot load file://users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-resources@0.12.1.js/focus.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ system.js:1020
system.js:1020 XMLHttpRequest cannot load file://users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-router@0.13.0.js/router-view.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ system.js:1020
system.js:1020 XMLHttpRequest cannot load file://users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-router@0.13.0.js/route-href.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ system.js:1020
jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:139 Unhandled promise rejection : file://Users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-resources@0.12.1.js/compose.js
    Error loading file://Users/guybedford/Projects/test/systemjs-bug-repro/jspm_packages/github/aurelia/templating-resources@0.12.1.js/compose.js
```

**Comment by EisenbergEffect** [comment]
So, do we just need to change our `normalize` calls to append a trailing slash? I'm confused as to what the change actually is in behavior and why this has been done.

**Comment by guybedford** [comment]
Yes exactly. The reason for this is that the locate hook and normalize hook are now just one hook in the new spec - resolve. So we resolve to URL in normalize now in the latest SystemJS in preparation for this (effectively deprecating the locate hook to be an identity operation). As a result automatic .js extensions which would have been added in locate are now added in normalize.

**Comment by EisenbergEffect** [comment]
I feel like this is going to cause us broader problems. I'm not sure just yet. Is there a way to not upgrade to the Beta?  I don't know when I'm going to have time to look into this. Not this week for sure.

**Comment by guybedford** [comment]
Basically it's caused by module names and URLs being able to exist side-by-side (`import '//cdn.jquery.com/jquery.js'`). As a result the simplest normalization system is to turn everything into a URL as the lowest common reference system. There's a broader discussion at https://github.com/whatwg/loader/issues/52 if you care to dive into the arguments as well. The beta is not currently installed via `npm install jspm`, only `npm install jspm@beta`. Do let me know when you are able to look into this, and I can adapt timelines here as well.

**Comment by guybedford** [comment]
To update on the exact issue here - 

``` javascript
System.normalize('templating-resources', parent).then(function(normalized) {
});
```

Will return `normalized` above as the package name, with the `".js"` extension added.

As far as I can guess, I think that is the issue for the dynamic import of `aurelia/templating-resources@0.12.1.js`.

**Comment by EisenbergEffect** [comment]
Ok, I think I know the set of scenarios where we do things like that. I will look into it. Is the change of adding the final slash backwards compatible with the current release version?

**Comment by guybedford** [comment]
Glad it's making sense! Yes, it should be as far as I'm aware.

**Comment by lzonjic** [comment]
@EisenbergEffect Is there any hope that this will be solved in near future? Is there any alternate way to make it work? Can I help in any way?

JSPM beta has support for TypeScript transpiler so it's very important for my stack (Aurelia + TS + ASP.NET 5 in VS Code), but today Aurelia doesn't work with JSPM beta...

**Comment by EisenbergEffect** [comment]
@lzonjic It won't be in today's releases, but we can address it soon after. If you want to submit a PR to fix the problem, you are welcome to. In my understanding, it mostly involves changes to how we call the normalize API which happens in the bootstrapper and in the loader-default libraries.

**Comment by guybedford** [comment]
I'm hoping to release the jspm beta as the main release very soon as it has a lot of important features. This is the blocker for that so please do keep me posted here.

**Comment by EisenbergEffect** [comment]
@guybedford Is there any way to do a synchronous normalize in the new version? Or is the api still the same, just with the change in behavior?

**Comment by EisenbergEffect** [comment]
Also, can you expand on what changes will likely be coming in the new version of the loader spec that might affect us?

**Comment by guybedford** [comment]
@EisenbergEffect yes there is `System.normalizeSync` but it is not documented as a stable API at the moment, although there are no plans to remove it. I'd still suggest using async normalize where you can though.

Did you want to know more about the changes already pushed or further changes in future?

**Comment by EisenbergEffect** [comment]
I'm interested in the future set of changes that are coming.

**Comment by EisenbergEffect** [comment]
@guybedford Do I need to install an updated version of jspm as well? or just the system.js loader? I'm looking into this now after updating to the beta loader and I'm getting a completely different set of errors. The bootstrapper module isn't even loading correctly.

**Comment by EisenbergEffect** [comment]
In my index.html file I have `System.import('aurelia-bootstrapper');` The result of that is that the bootstrapper module never loads. The define function is never run. Instead, an error occurs with respect to a dependency. Here are the errors I get:

system.src.js:3798 GET http://localhost:9000/dist/aurelia-logging-console.js 404 (Not Found)j @ system.src.js:3798o.fetch @ system.src.js:3798o.fetch @ system.src.js:3798p @ system.src.js:3798(anonymous function) @ system.src.js:3798a @ system.src.js:3798a @ system.src.js:3798n @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798
(index):1 Uncaught (in promise) Not Found: http://localhost:9000/dist/aurelia-logging-console.js
    Error loading http://localhost:9000/dist/aurelia-logging-console.js from http://localhost:9000/jspm_packages/github/aurelia/bootstrapper@0.14.0.js
    Error loading http://localhost:9000/dist/aurelia-logging-console.js
system.src.js:3798 GET http://localhost:9000/dist/process.js 404 (Not Found)j @ system.src.js:3798o.fetch @ system.src.js:3798o.fetch @ system.src.js:3798p @ system.src.js:3798(anonymous function) @ system.src.js:3798a @ system.src.js:3798a @ system.src.js:3798n @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798
system.src.js:3798 GET http://localhost:9000/dist/aurelia-logging.js 404 (Not Found)j @ system.src.js:3798o.fetch @ system.src.js:3798o.fetch @ system.src.js:3798p @ system.src.js:3798(anonymous function) @ system.src.js:3798a @ system.src.js:3798a @ system.src.js:3798n @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798
system.src.js:3798 GET http://localhost:9000/dist/aurelia-metadata.js 404 (Not Found)j @ system.src.js:3798o.fetch @ system.src.js:3798o.fetch @ system.src.js:3798p @ system.src.js:3798(anonymous function) @ system.src.js:3798a @ system.src.js:3798a @ system.src.js:3798n @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798
system.src.js:3798 GET http://localhost:9000/dist/aurelia-loader.js 404 (Not Found)j @ system.src.js:3798o.fetch @ system.src.js:3798o.fetch @ system.src.js:3798p @ system.src.js:3798(anonymous function) @ system.src.js:3798a @ system.src.js:3798a @ system.src.js:3798n @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798
system.src.js:3798 GET http://localhost:9000/dist/aurelia-path.js 404 (Not Found)j @ system.src.js:3798o.fetch @ system.src.js:3798o.fetch @ system.src.js:3798p @ system.src.js:3798(anonymous function) @ system.src.js:3798a @ system.src.js:3798a @ system.src.js:3798n @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798
system.src.js:3798 GET http://localhost:9000/dist/aurelia-templating.js 404 (Not Found)j @ system.src.js:3798o.fetch @ system.src.js:3798o.fetch @ system.src.js:3798p @ system.src.js:3798(anonymous function) @ system.src.js:3798a @ system.src.js:3798a @ system.src.js:3798n @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798
system.src.js:3798 GET http://localhost:9000/dist/aurelia-binding.js 404 (Not Found)j @ system.src.js:3798o.fetch @ system.src.js:3798o.fetch @ system.src.js:3798p @ system.src.js:3798(anonymous function) @ system.src.js:3798a @ system.src.js:3798a @ system.src.js:3798n @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798(anonymous function) @ system.src.js:3798
system.src.js:3798 GET http://localhost:9000/dist/aurelia-task-queue.js 404 (Not Found)

I'm stumped. I can't do anything here. Grab the latest skeleton and see. Unless the way jspm installs things has changed as well, and maybe it has, I don't know why this wouldn't work.

**Comment by lzonjic** [comment]
@EisenbergEffect You'll need to install jspm@beta. You can also read here https://github.com/systemjs/systemjs/issues/540 how to reproduce it...

**Comment by EisenbergEffect** [comment]
Got jspm beta installed. Now I am seeing what I expect. Thanks!

**Comment by EisenbergEffect** [comment]
Ok, I've got the fixes into framework (for plugin loading) and templating (for view loading). I will release the patched versions tomorrow.

**Comment by plwalters** [comment]
@EisenbergEffect Is the change backwards compatible?

**Comment by lzonjic** [comment]
@EisenbergEffect Excellent! I can hardly wait your patch. Thanks!

**Comment by alvarezmario** [comment]
Fixed in https://github.com/aurelia/templating/commit/4589ec25d95becd5866df5575775aebd865645ea and https://github.com/aurelia/framework/commit/5823c93370681bc61832a9f6b849da2faef21e3f

**Comment by damianof** [comment]
This might not be completely fixed. I have update to latest aurelia, 0.13.2, and getting a bunch of these 404 errors in the browser console (for templating-resources and templating-router):

/jspm_packages/github/aurelia/templating-resources@0.13.0/compose.html 404 (Not Found)
...
/jspm_packages/github/aurelia/templating-router@0.14.0/router-view.html
...

**Comment by damianof** [comment]
I have <body aurelia-app="main"> and in my main.js file i am loading aurelia-validation and datatables.
When i commented out the aurelia-validation line it works
export function configure(aurelia) {
aurelia.use
.standardConfiguration()
.developmentLogging()
.plugin('aurelia-validation')
.plugin('datatables');
aurelia
    .start()
    .then(a => a.setRoot()); 
}
I had 0.2.4 of aurelia-validation. So i upgraded to latest which is0.2.6, but still no luck
So not sure if aurelia-validation is still not up to date with this issue here , or maybe this one https://github.com/systemjs/systemjs/issues/540

**Comment by damianof** [comment]
Disregard my previous comment. I fixed this by modifying the config.js file for aurelia-validation:
"github:aurelia/validation@0.2.6": {
      "aurelia-binding": "github:aurelia/binding@0.8.1",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.0",
      "aurelia-templating": "github:aurelia/templating@0.13.2"
    }

**Comment by lmaspoch** [comment]
@damianof  I'm still having the 404 on the same html pages (same problem as you).  Once I added the code on the main.js to use the plugin 'aurelia-validation' it blew up my application.  I checked my config.js and the validation piece looks exactly like yours. I've tried deleting the jspm_packages folder and reinstalling it to no avail.  If you have any ideas I would really appreciate it, i put the main js code below and the config code as well for your review.

---

## Config

```
"github:aurelia/validation@0.2.6": {
  "aurelia-binding": "github:aurelia/binding@0.8.1",
  "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.0",
  "aurelia-templating": "github:aurelia/templating@0.13.2"
}
```

---

## Main

```
aurelia.use
        .standardConfiguration()
        .developmentLogging()
        .plugin("aurelia-validation");
```

**Comment by hellfyred** [comment]
@lmaspoch The steps outlined by @damianof worked for me but I ran `jspm update` before applying his config.js changes. Jspm said I was up to date and I could see the newer binding, DI and templating versions under jspm_packages but they were not applied to config.js. Manually setting the versions in config.js fixed my app with no more warnings being thrown. Running `jspm update` **after** making the version changes in config.js resulted in validation's deps reverting back to the older versions of binding, DI and templating, breaking my app again. Hope this helps and thank you @damianof for the fix!

**Comment by damianof** [comment]
@lmaspoch @rdmead223 Here is what i have in my aureliafile.js in addition of the config.js section above:

```
var aurelia = require('aurelia-cli');

  aurelia.command('bundle', {
    js: {
      "dist/app-bundle": {
        modules: [
          'dist/**/*.js',
          'aurelia-bootstrapper',
          'aurelia-http-client',
          'aurelia-router',
          'aurelia-animator-css',
          'github:aurelia/templating-binding@0.13.0',
          'github:aurelia/templating-resources@0.13.0',
          'github:aurelia/templating-router@0.14.0',
          'github:aurelia/loader-default@0.9.0',
          'github:aurelia/history-browser@0.6.1'
        ],
        options: {
          inject: true,
          minify: true
        }
      }
    },
    template: {
      "dist/app-bundle": {
        pattern: 'dist/**/*.html',
        options: {
          inject: true
        }
      }
    }
  });
```

Also here is my path in config.js:

```
"paths": {
    "*": "dist/*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js",
    "aurelia-skeleton-navigation/*": "lib/*.js"
  },
```

And here is currently my index.html (it's actually a server-side views served through express/ejs but you get the idea)

```
<body aurelia-app="main">
<base href="/dashboard">
<script src="jspm_packages/system.js"></script>
<script src="config.js"></script>
<script>
    System.config({
        'paths': {
            '*': 'dist/*.js'
        }
    });
```

Now, not sure how much it matters (and I dont think affects this issue in anyway), but all my aurelia project is inside a folder called 'frontend', which is inside my root for my node/express app. In express, i just serve the whole folder as static.

```
app.use(express.static(path.join(__dirname, 'frontend')));
```

NOTE: Myself and a couple of partners are building something great with Aurelia and we are targeting our beta to be live in 4 months. The company is called Entensive. Stay tuned on entensive.com and follow on twitter at @entensive as it will be our main channel to communicate when we are ready to launch.

**Comment by damianof** [comment]
Ok getting the same error again after trying upgrading to aurelia 1.0.0 beta 1. Here is my config,js file

```
System.config({
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime",
      "es7.decorators",
      "es7.classProperties"
    ]
  },
  "paths": {
    "*": "dist/*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  },
  "buildCSS": false
});

System.config({
  "map": {
    "aurelia-animator-css": "github:aurelia/animator-css@1.0.0-beta.1.0.1",
    "aurelia-bootstrapper": "github:aurelia/bootstrapper@1.0.0-beta.1",
    "aurelia-dependency-injection": "github:aurelia/dependency-injection@1.0.0-beta.1",
    "aurelia-event-aggregator": "github:aurelia/event-aggregator@1.0.0-beta.1",
    "aurelia-framework": "github:aurelia/framework@1.0.0-beta.1.0.1",
    "aurelia-http-client": "github:aurelia/http-client@1.0.0-beta.1",
    "aurelia-router": "github:aurelia/router@1.0.0-beta.1",
    "aurelia-validation": "github:aurelia/validation@0.2.8",
    "babel": "npm:babel-core@5.6.15",
    "babel-runtime": "npm:babel-runtime@5.6.15",
    "bootstrap": "github:twbs/bootstrap@3.3.5",
    "core-js": "npm:core-js@0.9.18",
    "css": "github:systemjs/plugin-css@0.1.19",
    "datatables": "github:DataTables/DataTables@1.10.7",
    "font-awesome": "npm:font-awesome@4.4.0",
    "jquery": "github:components/jquery@2.1.4",
    "socket.io-client": "npm:socket.io-client@1.3.5",
    "sortable": "github:rubaxa/sortable@1.4.2",
    "toastr": "github:CodeSeven/toastr@2.1.1",
    "github:CodeSeven/toastr@2.1.1": {
      "css": "github:systemjs/plugin-css@0.1.19",
      "jquery": "github:components/jquery@2.1.4"
    },
    "github:DataTables/DataTables@1.10.7": {
      "css": "github:systemjs/plugin-css@0.1.19",
      "jquery": "github:components/jquery@2.1.4"
    },
    "github:aurelia/animator-css@1.0.0-beta.1.0.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1"
    },
    "github:aurelia/binding@0.8.6": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-task-queue": "github:aurelia/task-queue@0.6.2",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/bootstrapper@1.0.0-beta.1": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.1",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.0.1",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.0.1",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.0.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "github:aurelia/dependency-injection@0.9.2": {
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/dependency-injection@1.0.0-beta.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "github:aurelia/event-aggregator@1.0.0-beta.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1"
    },
    "github:aurelia/framework@1.0.0-beta.1.0.1": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.0.1",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "github:aurelia/http-client@1.0.0-beta.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "github:aurelia/loader@0.8.7": {
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.2.0",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "core-js": "npm:core-js@0.9.18",
      "webcomponentsjs": "github:webcomponents/webcomponentsjs@0.6.3"
    },
    "github:aurelia/metadata@0.7.3": {
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/router@1.0.0-beta.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "github:aurelia/templating@0.14.4": {
      "aurelia-binding": "github:aurelia/binding@0.8.6",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.2.0",
      "aurelia-loader": "github:aurelia/loader@0.8.7",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "aurelia-task-queue": "github:aurelia/task-queue@0.6.2",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/validation@0.2.8": {
      "aurelia-binding": "github:aurelia/binding@0.8.6",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-templating": "github:aurelia/templating@0.14.4"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.5.2"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-net@0.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "timers": "github:jspm/nodelibs-timers@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-timers@0.1.0": {
      "timers-browserify": "npm:timers-browserify@1.4.1"
    },
    "github:jspm/nodelibs-tty@0.1.0": {
      "tty-browserify": "npm:tty-browserify@0.0.0"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "github:jspm/nodelibs-zlib@0.1.0": {
      "browserify-zlib": "npm:browserify-zlib@0.1.4"
    },
    "github:twbs/bootstrap@3.3.5": {
      "jquery": "github:components/jquery@2.1.4"
    },
    "npm:asn1.js@4.0.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@4.3.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-binding@1.0.0-beta.1.0.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-dependency-injection@1.0.0-beta.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-event-aggregator@1.0.0-beta.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1"
    },
    "npm:aurelia-framework@1.0.0-beta.1.0.1": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.0.1",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-history-browser@1.0.0-beta.1": {
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-loader-default@1.0.0-beta.1.0.1": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1"
    },
    "npm:aurelia-loader@1.0.0-beta.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1"
    },
    "npm:aurelia-logging-console@1.0.0-beta.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1"
    },
    "npm:aurelia-metadata@1.0.0-beta.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-pal-browser@1.0.0-beta.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1"
    },
    "npm:aurelia-route-recognizer@1.0.0-beta.1": {
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-router@1.0.0-beta.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-task-queue@1.0.0-beta.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1"
    },
    "npm:aurelia-templating-binding@1.0.0-beta.1": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.0.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1"
    },
    "npm:aurelia-templating-resources@1.0.0-beta.1.0.1": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.0.1",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-templating-router@1.0.0-beta.1.0.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1"
    },
    "npm:aurelia-templating@1.0.0-beta.1": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.0.1",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:babel-runtime@5.6.15": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:benchmark@1.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:better-assert@1.0.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "callsite": "npm:callsite@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:bindings@1.2.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:browserify-aes@1.0.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.2",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.5",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.0": {
      "bn.js": "npm:bn.js@4.3.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:browserify-sign@4.0.0": {
      "bn.js": "npm:bn.js@4.3.0",
      "browserify-rsa": "npm:browserify-rsa@4.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.0.2",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:browserify-zlib@0.1.4": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "pako": "npm:pako@0.2.8",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "readable-stream": "npm:readable-stream@1.1.13",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:buffer@3.5.2": {
      "base64-js": "npm:base64-js@0.0.8",
      "ieee754": "npm:ieee754@1.1.6",
      "is-array": "npm:is-array@1.0.1"
    },
    "npm:bufferutil@1.0.1": {
      "bindings": "npm:bindings@1.2.1",
      "nan": "npm:nan@1.6.2"
    },
    "npm:cipher-base@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@0.9.18": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.3.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.0.2"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.4"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.0",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.0",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:debug@0.7.4": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "tty": "github:jspm/nodelibs-tty@0.1.0"
    },
    "npm:debug@2.1.3": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ms": "npm:ms@0.7.0",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "tty": "github:jspm/nodelibs-tty@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@5.0.0": {
      "bn.js": "npm:bn.js@4.3.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:elliptic@6.0.2": {
      "bn.js": "npm:bn.js@4.3.0",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:engine.io-client@1.5.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "component-emitter": "npm:component-emitter@1.1.2",
      "component-inherit": "npm:component-inherit@0.0.3",
      "debug": "npm:debug@2.1.3",
      "engine.io-parser": "npm:engine.io-parser@1.2.1",
      "has-cors": "npm:has-cors@1.0.3",
      "indexof": "npm:indexof@0.0.1",
      "parsejson": "npm:parsejson@0.0.1",
      "parseqs": "npm:parseqs@0.0.2",
      "parseuri": "npm:parseuri@0.0.4",
      "ws": "npm:ws@0.7.1",
      "xmlhttprequest": "github:rase-/node-XMLHttpRequest@add%2Fssl-support"
    },
    "npm:engine.io-parser@1.2.1": {
      "after": "npm:after@0.8.1",
      "arraybuffer.slice": "npm:arraybuffer.slice@0.0.6",
      "base64-arraybuffer": "npm:base64-arraybuffer@0.1.2",
      "blob": "npm:blob@0.0.2",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "has-binary": "npm:has-binary@0.1.5",
      "utf8": "npm:utf8@2.0.0"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:font-awesome@4.4.0": {
      "css": "github:systemjs/plugin-css@0.1.19"
    },
    "npm:has-binary@0.1.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "isarray": "npm:isarray@0.0.1"
    },
    "npm:has-binary@0.1.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "isarray": "npm:isarray@0.0.1"
    },
    "npm:has-cors@1.0.3": {
      "global": "github:component/global@2.0.1"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.3.0",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:nan@1.6.2": {
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "npm:options@0.0.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:pako@0.2.8": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:parse-asn1@5.0.0": {
      "asn1.js": "npm:asn1.js@4.0.0",
      "browserify-aes": "npm:browserify-aes@1.0.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:parsejson@0.0.1": {
      "better-assert": "npm:better-assert@1.0.2"
    },
    "npm:parseqs@0.0.2": {
      "better-assert": "npm:better-assert@1.0.2"
    },
    "npm:parseuri@0.0.2": {
      "better-assert": "npm:better-assert@1.0.2"
    },
    "npm:parseuri@0.0.4": {
      "better-assert": "npm:better-assert@1.0.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.3.0",
      "browserify-rsa": "npm:browserify-rsa@4.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:randombytes@2.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sha.js@2.4.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:socket.io-client@1.3.5": {
      "backo2": "npm:backo2@1.0.2",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "component-bind": "npm:component-bind@1.0.0",
      "component-emitter": "npm:component-emitter@1.1.2",
      "debug": "npm:debug@0.7.4",
      "engine.io-client": "npm:engine.io-client@1.5.1",
      "has-binary": "npm:has-binary@0.1.6",
      "indexof": "npm:indexof@0.0.1",
      "object-component": "npm:object-component@0.0.3",
      "parseuri": "npm:parseuri@0.0.2",
      "socket.io-parser": "npm:socket.io-parser@2.2.4",
      "to-array": "npm:to-array@0.1.3"
    },
    "npm:socket.io-parser@2.2.4": {
      "benchmark": "npm:benchmark@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "component-emitter": "npm:component-emitter@1.1.2",
      "debug": "npm:debug@0.7.4",
      "isarray": "npm:isarray@0.0.1",
      "json3": "npm:json3@3.2.6"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.13"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:timers-browserify@1.4.1": {
      "process": "npm:process@0.11.2"
    },
    "npm:ultron@1.0.2": {
      "events": "github:jspm/nodelibs-events@0.1.1"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:utf-8-validate@1.0.1": {
      "bindings": "npm:bindings@1.2.1",
      "nan": "npm:nan@1.6.2"
    },
    "npm:utf8@2.0.0": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:ws@0.7.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "bufferutil": "npm:bufferutil@1.0.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "options": "npm:options@0.0.6",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "tls": "github:jspm/nodelibs-tls@0.1.0",
      "ultron": "npm:ultron@1.0.2",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "utf-8-validate": "npm:utf-8-validate@1.0.1",
      "util": "github:jspm/nodelibs-util@0.1.0",
      "zlib": "github:jspm/nodelibs-zlib@0.1.0"
    }
  }
});

```

**Comment by ArunaSelvaraj** [comment]
Hi,
I myself getting the same error for aurelia-templating 
**Error**:Unhandled promise rejection
Error: Access to restricted URI denied Error loading file:///C:/Users/aruna.selvaraj/Desktop/aurelia-ej-bridge/src/aurelia-templating.js

It searches in current folder for aurelia-templating rather then getting it from github

my config file consist of the following
 paths: {
    "*": "src/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
and in
map:{...
 "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.0"}
